### ISSUE TITLE
Contoh Format Issue dan Petunjuk untuk Kontributor

### ISSUE THREAD

**Issue by ariaseta** [kodingworks/flutter-works-boilerplate#1]
kayaknya belum ada petunjuk untuk kontribusi ya? @wisnuwiry 

Termasuk format issue

**Comment by wisnuwiry** [comment]
## Issue Template:

![image](https://user-images.githubusercontent.com/44025097/107529470-7b995680-6bed-11eb-935e-e8c778ca56b3.png)
![image](https://user-images.githubusercontent.com/44025097/107529539-8b189f80-6bed-11eb-88f6-c2c5ec7eb188.png)
![image](https://user-images.githubusercontent.com/44025097/107529577-966bcb00-6bed-11eb-9e93-c7279bc253da.png)


## Merge Request Template:

![image](https://user-images.githubusercontent.com/44025097/107529714-bc916b00-6bed-11eb-8037-eb9f6ba7c13c.png)


## Petunjuk Contributing:

![image](https://user-images.githubusercontent.com/44025097/107529831-de8aed80-6bed-11eb-83bd-8fb7137735d3.png)


cc: @ariaseta

**Comment by ariaseta** [comment]
oke done, aku closed ya @wisnuwiry 
jangan lupa set license MIT
